version: '3.3'

volumes:
  redis-data: null

networks:
  bvb:

services:
  redis:
    image: redis
    command: redis-server --requirepass password
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/data'
    networks:
      - bvb

  jobs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - bvb