# Name of your application. Used to uniquely configure containers.
service: bitcoinvaluebot

# Name of the container image.
image: acidtib/bitcoinvaluebot

# Deploy to these servers.
servers:
  web:
    traefik: false
    hosts:
      - 51.89.219.181

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  server: ghcr.io
  username: acidtib
  password:
    - GITHUB_TOKEN

# Inject ENV variables into containers (secrets come from .env).
env:
  clear:
    APP_ENV: production
  secret:
    - COINMARKETCAP_API_KEY
    - TWITTER_CONSUMER_KEY
    - TWITTER_CONSUMER_SECRET
    - TWITTER_ACCESS_TOKEN
    - TWITTER_ACCESS_TOKEN_SECRET
    - REDIS_URL

# Call a broadcast command on deploys.
# audit_broadcast_cmd:
#   bin/broadcast_to_bc

# Use a different ssh user than root
# ssh:
#   user: app

# Configure builder setup.
builder:
  dockerfile: Dockerfile
  multiarch: false
  secrets:
    - GITHUB_TOKEN

# Use accessory services (secrets come from .env).
accessories:
  redis:
    image: redis:7.0
    cmd: redis-server --requirepass <%= ENV['REDIS_PASSWORD'] %>
    host: 51.89.219.181
    port: "6390:6379"
    directories:
      - dataRedis:/data

# Configure custom arguments for Traefik
# traefik:
#   args:
#     accesslog: true
#     accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
#   path: /healthz
#   port: 4000
  skip: true
